"""Added Presence Health Browsing Data Table

Revision ID: 48032ee3ef4f
Revises: 
Create Date: 2017-03-15 10:10:27.363353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48032ee3ef4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presencebrowsingdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cookie_id', sa.String(length=10000), nullable=True),
    sa.Column('oncology_clicks', sa.Integer(), nullable=True),
    sa.Column('oncology_hover_time', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presencebrowsingdata')
    # ### end Alembic commands ###
