"""removed_cookie_id_field_from_presencebrowsingdata_table

Revision ID: a31d1c1d12af
Revises: 69b0bfeafe08
Create Date: 2017-08-29 16:23:38.843455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a31d1c1d12af'
down_revision = '69b0bfeafe08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('presencebrowsingdata', 'cookie_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presencebrowsingdata', sa.Column('cookie_id', sa.VARCHAR(length=10000), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
