"""added presence health intent keywords

Revision ID: 2e4d69d668c6
Revises: a31d1c1d12af
Create Date: 2017-10-30 10:45:33.648982

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e4d69d668c6'
down_revision = 'a31d1c1d12af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presence_browsing_intent_snapshot', sa.Column('benefits_clicks', sa.Integer(), server_default=sa.text(u'0'), nullable=False))
    op.add_column('presence_browsing_intent_snapshot', sa.Column('benefits_hover_time', sa.Float(), server_default=sa.text(u'0.0'), nullable=False))
    op.add_column('presence_browsing_intent_snapshot', sa.Column('endocrinology_clicks', sa.Integer(), server_default=sa.text(u'0'), nullable=False))
    op.add_column('presence_browsing_intent_snapshot', sa.Column('endocrinology_hover_time', sa.Float(), server_default=sa.text(u'0.0'), nullable=False))
    op.add_column('presence_browsing_intent_snapshot', sa.Column('enrollment_clicks', sa.Integer(), server_default=sa.text(u'0'), nullable=False))
    op.add_column('presence_browsing_intent_snapshot', sa.Column('enrollment_hover_time', sa.Float(), server_default=sa.text(u'0.0'), nullable=False))
    op.add_column('presence_browsing_intent_snapshot', sa.Column('orthopedics_clicks', sa.Integer(), server_default=sa.text(u'0'), nullable=False))
    op.add_column('presence_browsing_intent_snapshot', sa.Column('orthopedics_hover_time', sa.Float(), server_default=sa.text(u'0.0'), nullable=False))
    op.add_column('presence_browsing_intent_snapshot', sa.Column('womens_health_clicks', sa.Integer(), server_default=sa.text(u'0'), nullable=False))
    op.add_column('presence_browsing_intent_snapshot', sa.Column('womens_health_hover_time', sa.Float(), server_default=sa.text(u'0.0'), nullable=False))
    op.alter_column('presence_browsing_intent_snapshot', 'oncology_clicks',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('presence_browsing_intent_snapshot', 'oncology_hover_time',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.add_column('presencebrowsingdata', sa.Column('benefits_clicks', sa.Integer(), server_default=sa.text(u'0'), nullable=False))
    op.add_column('presencebrowsingdata', sa.Column('benefits_hover_time', sa.Float(), server_default=sa.text(u'0.0'), nullable=False))
    op.add_column('presencebrowsingdata', sa.Column('endocrinology_clicks', sa.Integer(), server_default=sa.text(u'0'), nullable=False))
    op.add_column('presencebrowsingdata', sa.Column('endocrinology_hover_time', sa.Float(), server_default=sa.text(u'0.0'), nullable=False))
    op.add_column('presencebrowsingdata', sa.Column('enrollment_clicks', sa.Integer(), server_default=sa.text(u'0'), nullable=False))
    op.add_column('presencebrowsingdata', sa.Column('enrollment_hover_time', sa.Float(), server_default=sa.text(u'0.0'), nullable=False))
    op.add_column('presencebrowsingdata', sa.Column('orthopedics_clicks', sa.Integer(), server_default=sa.text(u'0'), nullable=False))
    op.add_column('presencebrowsingdata', sa.Column('orthopedics_hover_time', sa.Float(), server_default=sa.text(u'0.0'), nullable=False))
    op.add_column('presencebrowsingdata', sa.Column('womens_health_clicks', sa.Integer(), server_default=sa.text(u'0'), nullable=False))
    op.add_column('presencebrowsingdata', sa.Column('womens_health_hover_time', sa.Float(), server_default=sa.text(u'0.0'), nullable=False))
    op.alter_column('presencebrowsingdata', 'oncology_clicks',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('presencebrowsingdata', 'oncology_hover_time',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('presencebrowsingdata', 'oncology_hover_time',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('presencebrowsingdata', 'oncology_clicks',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('presencebrowsingdata', 'womens_health_hover_time')
    op.drop_column('presencebrowsingdata', 'womens_health_clicks')
    op.drop_column('presencebrowsingdata', 'orthopedics_hover_time')
    op.drop_column('presencebrowsingdata', 'orthopedics_clicks')
    op.drop_column('presencebrowsingdata', 'enrollment_hover_time')
    op.drop_column('presencebrowsingdata', 'enrollment_clicks')
    op.drop_column('presencebrowsingdata', 'endocrinology_hover_time')
    op.drop_column('presencebrowsingdata', 'endocrinology_clicks')
    op.drop_column('presencebrowsingdata', 'benefits_hover_time')
    op.drop_column('presencebrowsingdata', 'benefits_clicks')
    op.alter_column('presence_browsing_intent_snapshot', 'oncology_hover_time',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('presence_browsing_intent_snapshot', 'oncology_clicks',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('presence_browsing_intent_snapshot', 'womens_health_hover_time')
    op.drop_column('presence_browsing_intent_snapshot', 'womens_health_clicks')
    op.drop_column('presence_browsing_intent_snapshot', 'orthopedics_hover_time')
    op.drop_column('presence_browsing_intent_snapshot', 'orthopedics_clicks')
    op.drop_column('presence_browsing_intent_snapshot', 'enrollment_hover_time')
    op.drop_column('presence_browsing_intent_snapshot', 'enrollment_clicks')
    op.drop_column('presence_browsing_intent_snapshot', 'endocrinology_hover_time')
    op.drop_column('presence_browsing_intent_snapshot', 'endocrinology_clicks')
    op.drop_column('presence_browsing_intent_snapshot', 'benefits_hover_time')
    op.drop_column('presence_browsing_intent_snapshot', 'benefits_clicks')
    # ### end Alembic commands ###
