"""added_browsing_intent_snapshot_table_and_date_fields_to_browsing_data_table

Revision ID: ff5a4e3cacbf
Revises: 70c67b81da38
Create Date: 2017-08-29 11:01:15.056502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff5a4e3cacbf'
down_revision = '70c67b81da38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presence_browsing_intent_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presence_browsing_session_data_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('calculated_intent', sa.Text(), nullable=True),
    sa.Column('intent_formula_version', sa.Text(), nullable=True),
    sa.Column('oncology_hover_time', sa.Float(), nullable=True),
    sa.Column('oncology_clicks', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['presence_browsing_session_data_id'], ['presencebrowsingdata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'presencebrowsingdata', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column(u'presencebrowsingdata', sa.Column('date_last_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'presencebrowsingdata', 'date_last_updated')
    op.drop_column(u'presencebrowsingdata', 'date_created')
    op.drop_table('presence_browsing_intent_snapshot')
    # ### end Alembic commands ###
